[phases.install]
cmds = ["echo 'Skipping root install'"]

[phases.build]
cmds = [
  "cd server && npm ci",
  "cd server && npx tsc --skipLibCheck"
]

[start]
cmd = "node server/dist/http-server.js"

[variables]
NODE_ENV = "production"
