[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd server && node dist/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
