[build]
  builder = "nixpacks"

[deploy]
  startCommand = "cd server && npm start"
  healthcheckPath = "/health"
  healthcheckTimeout = 100
  restartPolicyType = "on-failure"
  restartPolicyMaxRetries = 10
