[build]
builder = "nixpacks"

[deploy]
startCommand = "cd server && node dist/http-server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on-failure"der = "nixpacks"

[deploy]
  startCommand = "cd server && node dist/http-server.js"
  healthcheckPath = "/health"
  healthcheckTimeout = 300
  restartPolicyType = "on-failure"  builder = "nixpacks"

[deploy]
  startCommand = "cd server && npm start"
  healthcheckPath = "/health"
  healthcheckTimeout = 100
  restartPolicyType = "on-failure"
  restartPolicyMaxRetries = 10
